### ISSUE TITLE
为什么不直接向Redis提交PR

### ISSUE THREAD

**Issue by QingLeiLi** [alibaba/ApsaraCache#8]
看描述是基于Redis的拓展和优化，在存在Redis的情况下，为什么要选择重新造一个轮子，而不是完善现有的Redis？
公司是出于什么方面的考量呢？

**Comment by zeroonead** [comment]
直接向Redis提交PR 主导权都不在自己手上,另外开个项目,自己想怎么改就怎么改

**Comment by QingLeiLi** [comment]
总感觉轮子会满天飞，其他公司要开源新功能，要主导权的话，就又有了一个轮子
